// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WorkoutsImport } from './routes/workouts'
import { Route as ProgramsImport } from './routes/programs'
import { Route as MuscleGroupsImport } from './routes/muscle-groups'
import { Route as ExercisesImport } from './routes/exercises'
import { Route as IndexImport } from './routes/index'
import { Route as WorkoutIdImport } from './routes/workout/$id'
import { Route as ProgramIdImport } from './routes/program/$id'
import { Route as MuscleGroupIdImport } from './routes/muscle-group/$id'
import { Route as ExerciseIdImport } from './routes/exercise/$id'

// Create/Update Routes

const WorkoutsRoute = WorkoutsImport.update({
  path: '/workouts',
  getParentRoute: () => rootRoute,
} as any)

const ProgramsRoute = ProgramsImport.update({
  path: '/programs',
  getParentRoute: () => rootRoute,
} as any)

const MuscleGroupsRoute = MuscleGroupsImport.update({
  path: '/muscle-groups',
  getParentRoute: () => rootRoute,
} as any)

const ExercisesRoute = ExercisesImport.update({
  path: '/exercises',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkoutIdRoute = WorkoutIdImport.update({
  path: '/workout/$id',
  getParentRoute: () => rootRoute,
} as any)

const ProgramIdRoute = ProgramIdImport.update({
  path: '/program/$id',
  getParentRoute: () => rootRoute,
} as any)

const MuscleGroupIdRoute = MuscleGroupIdImport.update({
  path: '/muscle-group/$id',
  getParentRoute: () => rootRoute,
} as any)

const ExerciseIdRoute = ExerciseIdImport.update({
  path: '/exercise/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/exercises': {
      preLoaderRoute: typeof ExercisesImport
      parentRoute: typeof rootRoute
    }
    '/muscle-groups': {
      preLoaderRoute: typeof MuscleGroupsImport
      parentRoute: typeof rootRoute
    }
    '/workouts': {
      preLoaderRoute: typeof WorkoutsImport
      parentRoute: typeof rootRoute
    }
    '/exercise/$id': {
      preLoaderRoute: typeof ExerciseIdImport
      parentRoute: typeof rootRoute
    }
    '/muscle-group/$id': {
      preLoaderRoute: typeof MuscleGroupIdImport
      parentRoute: typeof rootRoute
    }
    '/workout/$id': {
      preLoaderRoute: typeof WorkoutIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ExercisesRoute,
  MuscleGroupsRoute,
  WorkoutsRoute,
  ExerciseIdRoute,
  MuscleGroupIdRoute,
  WorkoutIdRoute,
])
